# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 欢迎!
subtitle: '欢迎来到 LynxCatTheThird 的小窝儿'
description: '我是山猫三号，一个来自一百零三世纪的强人工智能。'
keywords:
author: LynxCatTheThird
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://www.lynx3.top/
permalink: :year/:month/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
    enable: false
    line_number: true
    auto_detect: false
    tab_replace: ""
    wrap: true
    hljs: false
prismjs:
    enable: false
    preprocess: true
    line_number: true
    tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
### Markdown
markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: true
    langPrefix: ''
    breaks: false
    linkify: true
    typographer: false
  plugins:
    - markdown-it-abbr # 注释
    # - markdown-it-attrs # 附加属性
    # - markdown-it-cjk-breaks # 抑制东亚字符之间的换行
    - name: markdown-it-container # 自定义块
      options: 
        danger
    - name: markdown-it-container
      options: 
        success
    - name: markdown-it-container
      options: 
        tips
    - name: markdown-it-container
      options: 
        warning
    - markdown-it-deflist # 定义列表
    - markdown-it-emoji # 表情
    - markdown-it-footnote # 脚注
    - markdown-it-ins # 插入（下划线）
    - markdown-it-mark # 标记（高亮）
    - markdown-it-sup # 上标
    - markdown-it-sub # 下标
  anchors:
    level: 1
  inline: false  # https://markdown-it.github.io/markdown-it/#MarkdownIt.renderInline
### Links
abbrlink:
  alg: crc32      #support crc16(default) and crc32
  rep: hex        #support dec(default) and hex
  drafts: false   #(true)Process draft,(false)Do not process draft. false(default) 
  # Generate categories from directory-tree
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
    enable: true  #true(default)
    depth:        #3(default)
    over_write: false 
  auto_title: false #enable auto title, it can auto fill the title by path
  auto_date: false #enable auto date, it can auto fill the date by time today
  force: false #enable force mode,in this mode, the plugin will ignore the cache, and calc the abbrlink for every post even it already had abbrlink. This only updates abbrlink rather than other front variables.
nofollow:
  enable: true
  field: site
  exclude:
    - 'exclude1.com'
    - 'exclude2.com'
### Search
search:
  path: search.xml
  field: post
  content: true
  format: html
### Sitemap
sitemap:
  path: 
    - sitemap.xml
    - sitemap.txt
  rel: true
  tags: true
  categories: true
### Swpp
swpp:
  # 是否启用插件
  enable: true
  # 是否在发布前自动执行脚本
  # auto_exec: true
  # 构建时拉取版本文件的警告等级，缺省为 1（该功能仅在 swpp-backends 版本号 >= 2.1.2 时可用）
  # 0 - 表示不允许出现 404 情况；1 - 表示允许服务器返回 404 状态码；2 - 表示允许任何 404（包括 DNS 解析失败等）
  warn_level: 1
  # 检查版本的 URL，不能以 '/' 结尾
  # npm_url: 'https://registry.npmmirror.com'
### Minify
uglify:
  mangle: true
  output:
  compress:
  exclude:
    - "*.min.js"
clean_css:
  exclude:
    - "*.min.css"
html_minifier:
  collapseBooleanAttributes: true
  collapseWhitespace: true
  ignoreCustomComments: [!!js/regexp /^\s*more/]
  removeComments: true
  removeEmptyAttributes: true
  removeScriptTypeAttributes: true
  removeStyleLinkTypeAttributes: true
  minifyJS: true
  minifyCSS: true
## Themes: https://hexo.io/themes/
theme: particlex

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repository: git@github.com:LynxCatTheThird/lynxcatthethird.github.io.git
    branch: main
  - type: git
    repository: git@github.com:ara1145/ara1145.github.io.git
    branch: main
